# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'winkler.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(907, 720)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_upper = QtWidgets.QHBoxLayout()
        self.horizontalLayout_upper.setObjectName("horizontalLayout_upper")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lcdNumber_dispensed = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_dispensed.sizePolicy().hasHeightForWidth())
        self.lcdNumber_dispensed.setSizePolicy(sizePolicy)
        self.lcdNumber_dispensed.setMinimumSize(QtCore.QSize(160, 80))
        self.lcdNumber_dispensed.setBaseSize(QtCore.QSize(160, 100))
        self.lcdNumber_dispensed.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"color: rgb(0, 255, 0);")
        self.lcdNumber_dispensed.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_dispensed.setObjectName("lcdNumber_dispensed")
        self.verticalLayout_2.addWidget(self.lcdNumber_dispensed)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lcdNumber_endpoint = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_endpoint.sizePolicy().hasHeightForWidth())
        self.lcdNumber_endpoint.setSizePolicy(sizePolicy)
        self.lcdNumber_endpoint.setMinimumSize(QtCore.QSize(160, 80))
        self.lcdNumber_endpoint.setStyleSheet("color:rgb(0, 255, 0);\n"
"background-color: rgb(40, 40, 40);\n"
"border-color: rgb(0, 116, 0);")
        self.lcdNumber_endpoint.setSmallDecimalPoint(False)
        self.lcdNumber_endpoint.setDigitCount(5)
        self.lcdNumber_endpoint.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_endpoint.setProperty("value", 0.0)
        self.lcdNumber_endpoint.setProperty("intValue", 0)
        self.lcdNumber_endpoint.setObjectName("lcdNumber_endpoint")
        self.verticalLayout_2.addWidget(self.lcdNumber_endpoint)
        self.pushButton_titrate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_titrate.sizePolicy().hasHeightForWidth())
        self.pushButton_titrate.setSizePolicy(sizePolicy)
        self.pushButton_titrate.setMinimumSize(QtCore.QSize(160, 100))
        self.pushButton_titrate.setMaximumSize(QtCore.QSize(140, 16777215))
        self.pushButton_titrate.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_titrate.setFont(font)
        self.pushButton_titrate.setStyleSheet("")
        self.pushButton_titrate.setFlat(False)
        self.pushButton_titrate.setObjectName("pushButton_titrate")
        self.verticalLayout_2.addWidget(self.pushButton_titrate)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.comboBox_flasks = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_flasks.sizePolicy().hasHeightForWidth())
        self.comboBox_flasks.setSizePolicy(sizePolicy)
        self.comboBox_flasks.setMinimumSize(QtCore.QSize(160, 0))
        self.comboBox_flasks.setBaseSize(QtCore.QSize(2, 0))
        self.comboBox_flasks.setObjectName("comboBox_flasks")
        self.verticalLayout_2.addWidget(self.comboBox_flasks)
        self.horizontalLayout_upper.addLayout(self.verticalLayout_2)
        self.widget_MPL = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.widget_MPL.sizePolicy().hasHeightForWidth())
        self.widget_MPL.setSizePolicy(sizePolicy)
        self.widget_MPL.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_MPL.setBaseSize(QtCore.QSize(4, 0))
        self.widget_MPL.setObjectName("widget_MPL")
        self.horizontalLayout_upper.addWidget(self.widget_MPL)
        self.verticalLayout.addLayout(self.horizontalLayout_upper)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_lower = QtWidgets.QHBoxLayout()
        self.horizontalLayout_lower.setObjectName("horizontalLayout_lower")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_1uL = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1uL.setObjectName("pushButton_1uL")
        self.verticalLayout_6.addWidget(self.pushButton_1uL)
        self.pushButton_10uL = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10uL.setObjectName("pushButton_10uL")
        self.verticalLayout_6.addWidget(self.pushButton_10uL)
        self.pushButton_100uL = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_100uL.setObjectName("pushButton_100uL")
        self.verticalLayout_6.addWidget(self.pushButton_100uL)
        self.pushButton_1000uL = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1000uL.setObjectName("pushButton_1000uL")
        self.verticalLayout_6.addWidget(self.pushButton_1000uL)
        self.pushButton_5000uL = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5000uL.setObjectName("pushButton_5000uL")
        self.verticalLayout_6.addWidget(self.pushButton_5000uL)
        self.horizontalLayout_lower.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lcdNumber_customvol = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_customvol.sizePolicy().hasHeightForWidth())
        self.lcdNumber_customvol.setSizePolicy(sizePolicy)
        self.lcdNumber_customvol.setMinimumSize(QtCore.QSize(120, 60))
        self.lcdNumber_customvol.setBaseSize(QtCore.QSize(120, 60))
        self.lcdNumber_customvol.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_customvol.setObjectName("lcdNumber_customvol")
        self.verticalLayout_5.addWidget(self.lcdNumber_customvol)
        self.horizontalSlider_dispense = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_dispense.setMaximum(100)
        self.horizontalSlider_dispense.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dispense.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_dispense.setTickInterval(5)
        self.horizontalSlider_dispense.setObjectName("horizontalSlider_dispense")
        self.verticalLayout_5.addWidget(self.horizontalSlider_dispense)
        self.pushButton_customvol = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_customvol.setStyleSheet("")
        self.pushButton_customvol.setObjectName("pushButton_customvol")
        self.verticalLayout_5.addWidget(self.pushButton_customvol)
        self.horizontalLayout_lower.addLayout(self.verticalLayout_5)
        self.pushButton_flask = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_flask.setMinimumSize(QtCore.QSize(160, 100))
        self.pushButton_flask.setBaseSize(QtCore.QSize(0, 100))
        self.pushButton_flask.setObjectName("pushButton_flask")
        self.horizontalLayout_lower.addWidget(self.pushButton_flask)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_lower.addItem(spacerItem)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox_gran = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_gran.setFont(font)
        self.checkBox_gran.setObjectName("checkBox_gran")
        self.verticalLayout_8.addWidget(self.checkBox_gran)
        self.checkBox_zoom = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_zoom.setFont(font)
        self.checkBox_zoom.setObjectName("checkBox_zoom")
        self.verticalLayout_8.addWidget(self.checkBox_zoom)
        self.checkBox_rapid = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_rapid.setFont(font)
        self.checkBox_rapid.setObjectName("checkBox_rapid")
        self.verticalLayout_8.addWidget(self.checkBox_rapid)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.spinBox_guess = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spinBox_guess.setFont(font)
        self.spinBox_guess.setMaximum(2000)
        self.spinBox_guess.setSingleStep(100)
        self.spinBox_guess.setProperty("value", 1000)
        self.spinBox_guess.setObjectName("spinBox_guess")
        self.verticalLayout_8.addWidget(self.spinBox_guess)
        self.horizontalLayout_lower.addLayout(self.verticalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_lower.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_connect = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_connect.setFont(font)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.verticalLayout_4.addWidget(self.pushButton_connect)
        self.pushButton_reload = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reload.setObjectName("pushButton_reload")
        self.verticalLayout_4.addWidget(self.pushButton_reload)
        self.label_meter = QtWidgets.QLabel(self.centralwidget)
        self.label_meter.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_meter.setObjectName("label_meter")
        self.verticalLayout_4.addWidget(self.label_meter)
        self.comboBox_meter = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_meter.setObjectName("comboBox_meter")
        self.verticalLayout_4.addWidget(self.comboBox_meter)
        self.label_port = QtWidgets.QLabel(self.centralwidget)
        self.label_port.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_port.setObjectName("label_port")
        self.verticalLayout_4.addWidget(self.label_port)
        self.comboBox_pump = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_pump.setObjectName("comboBox_pump")
        self.verticalLayout_4.addWidget(self.comboBox_pump)
        self.horizontalLayout_lower.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_lower)
        self.verticalLayout.setStretch(0, 3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 907, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLoad = QtWidgets.QMenu(self.menubar)
        self.menuLoad.setObjectName("menuLoad")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuLoad.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_meter.setCurrentIndex(-1)
        self.horizontalSlider_dispense.sliderMoved['int'].connect(self.lcdNumber_customvol.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Winkler Titrator"))
        self.label.setText(_translate("MainWindow", "Volume Dispensed"))
        self.label_2.setText(_translate("MainWindow", "Estimated Endpoint"))
        self.pushButton_titrate.setText(_translate("MainWindow", "Titrate!"))
        self.label_3.setText(_translate("MainWindow", "Select Flask"))
        self.pushButton_1uL.setText(_translate("MainWindow", "1 uL"))
        self.pushButton_10uL.setText(_translate("MainWindow", "10 uL"))
        self.pushButton_100uL.setText(_translate("MainWindow", "100 uL"))
        self.pushButton_1000uL.setText(_translate("MainWindow", "1000 uL"))
        self.pushButton_5000uL.setText(_translate("MainWindow", "5000 uL"))
        self.pushButton_customvol.setText(_translate("MainWindow", "Dispense"))
        self.pushButton_flask.setText(_translate("MainWindow", "Load Flask Cal"))
        self.checkBox_gran.setText(_translate("MainWindow", "Gran View"))
        self.checkBox_zoom.setText(_translate("MainWindow", "Zoom View"))
        self.checkBox_rapid.setText(_translate("MainWindow", "Rapid Mode"))
        self.label_4.setText(_translate("MainWindow", "Initial Guess (uL)"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect"))
        self.pushButton_reload.setText(_translate("MainWindow", "Reload Ports"))
        self.label_meter.setText(_translate("MainWindow", "Select meter COM port"))
        self.label_port.setText(_translate("MainWindow", "Select pump COM port"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuLoad.setTitle(_translate("MainWindow", "Load"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

